[package]
name = "vestry"
version.workspace = true
edition.workspace = true

[[bin]]
name  = "vestry"
path = "src/main.rs"

[dependencies]
haven_common.workspace = true
clap.workspace = true
toml.workspace = true
serde.workspace = true
colored = "3.1.1"

[dev-dependencies]
tempfile.workspace = true
